export type TaskStatus = "Not Started" | "In Progress" | "Review";

export const maxTaskTags = 10;

export type TaskTags =
  | []
  | [string]
  | [string, string]
  | [string, string, string]
  | [string, string, string, string]
  | [string, string, string, string, string]
  | [string, string, string, string, string, string]
  | [string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string, string]
  | [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string
    ];

export type ProjectTask = {
  id: string;
  isFinished: boolean;
  subject: string;
  status: TaskStatus;
  dueDate: string;
  priority: "Low" | "Medium" | "High";
  wikiPageLink: string;
  tags: TaskTags;
  milestone: string;
  details: string;
  children?: ProjectTask[];
};

export const boardStatuses: TaskStatus[] = [
  "Not Started",
  "In Progress",
  "Review",
];

export const tasks: ProjectTask[] = [
  {
    id: "task-1",
    isFinished: true,
    subject: "Reflect issue hierarchy rules in the UI",
    status: "Not Started",
    dueDate: "2026-05-24",
    priority: "High",
    wikiPageLink: "/project-wiki",
    tags: ["requirements", "wiki", "planning", "test1", "test2", "test3", "test4", "test5", "test6", "test7"],
    milestone: "ph-1-0",
    details: "Organize the relationship between Project Wiki and Task Wiki.",
    children: [
      {
        id: "task-1-child-1",
        isFinished: true,
        subject: "Define parent and child task display rules",
        status: "Review",
        dueDate: "2026-05-22",
        priority: "Medium",
        wikiPageLink: "/task-wiki",
        tags: ["requirements", "grid"],
        milestone: "ph-1-0",
        details: "Clarify how nested tasks appear in the project grid.",
      },
      {
        id: "task-1-child-2",
        isFinished: false,
        subject: "Check expansion behavior with nested records",
        status: "In Progress",
        dueDate: "2026-05-23",
        priority: "Medium",
        wikiPageLink: "/task-wiki",
        tags: ["grid", "qa"],
        milestone: "ph-1-0",
        details: "Verify that child task rows are shown only when expanded.",
        children: [
          {
            id: "task-1-child-2-grandchild-1",
            isFinished: false,
            subject: "Verify grandchild row notation",
            status: "Not Started",
            dueDate: "2026-05-24",
            priority: "Low",
            wikiPageLink: "/task-wiki",
            tags: ["grid", "qa"],
            milestone: "ph-1-0",
            details:
              "Confirm that grandchild task rows use the expected hierarchy marker.",
          },
        ],
      },
    ],
  },
  {
    id: "task-2",
    isFinished: false,
    subject: "Project list screen",
    status: "In Progress",
    dueDate: "2026-05-27",
    priority: "Medium",
    wikiPageLink: "/project-wiki",
    tags: ["ui", "navigation"],
    milestone: "ph-1-0",
    details: "Create a UI that navigates from the list to each project page.",
  },
  {
    id: "task-3",
    isFinished: false,
    subject: "Wiki Markdown input",
    status: "Review",
    dueDate: "2026-05-30",
    priority: "Medium",
    wikiPageLink: "/task-wiki",
    tags: ["wiki", "markdown", "editor"],
    milestone: "ph-1-1",
    details: "Place a Markdown input area on the Task Page.",
  },
  {
    id: "task-4",
    isFinished: false,
    subject: "Board view layout",
    status: "In Progress",
    dueDate: "2026-06-02",
    priority: "Low",
    wikiPageLink: "/project-wiki",
    tags: ["board", "layout"],
    milestone: "ph-1-1",
    details: "Show task cards grouped by status in board columns.",
  },
  {
    id: "task-5",
    isFinished: false,
    subject: "Task detail drawer",
    status: "Not Started",
    dueDate: "2026-06-04",
    priority: "High",
    wikiPageLink: "/task-wiki",
    tags: ["task", "detail", "drawer"],
    milestone: "ph-1-1",
    details: "Design a compact task detail drawer for quick edits.",
  },
  {
    id: "task-6",
    isFinished: false,
    subject: "Project dashboard metrics",
    status: "In Progress",
    dueDate: "2026-06-06",
    priority: "Medium",
    wikiPageLink: "/project-wiki",
    tags: ["dashboard", "metrics", "project"],
    milestone: "ph-1-1",
    details: "Add summary metrics for open tasks, reviews, and due dates.",
  },
  {
    id: "task-7",
    isFinished: true,
    subject: "Settings theme toggle",
    status: "Review",
    dueDate: "2026-06-08",
    priority: "Low",
    wikiPageLink: "/project-wiki",
    tags: ["settings", "theme"],
    milestone: "ph-1-1",
    details: "Review the theme toggle behavior in settings.",
  },
  {
    id: "task-8",
    isFinished: false,
    subject: "Tag search result filters",
    status: "Not Started",
    dueDate: "2026-06-10",
    priority: "Medium",
    wikiPageLink: "/project-wiki",
    tags: ["tag", "search", "filters"],
    milestone: "ph-1-2",
    details: "Let users narrow search results by tag, status, and priority.",
  },
  {
    id: "task-9",
    isFinished: false,
    subject: "Wiki link preview",
    status: "In Progress",
    dueDate: "2026-06-12",
    priority: "Medium",
    wikiPageLink: "/task-wiki",
    tags: ["wiki", "preview", "links"],
    milestone: "ph-1-2",
    details: "Show a lightweight preview when hovering over wiki links.",
  },
  {
    id: "task-10",
    isFinished: false,
    subject: "Milestone progress indicator",
    status: "Review",
    dueDate: "2026-06-14",
    priority: "High",
    wikiPageLink: "/project-wiki",
    tags: ["milestone", "progress", "status"],
    milestone: "ph-1-2",
    details: "Add milestone progress based on completed and review tasks.",
  },
  {
    id: "task-11",
    isFinished: false,
    subject: "Bulk task selection",
    status: "Not Started",
    dueDate: "2026-06-16",
    priority: "High",
    wikiPageLink: "/project-wiki",
    tags: ["bulk", "selection", "grid"],
    milestone: "ph-1-2",
    details: "Support selecting multiple tasks from the grid view.",
  },
  {
    id: "task-12",
    isFinished: true,
    subject: "Sidebar keyboard navigation",
    status: "Review",
    dueDate: "2026-06-18",
    priority: "Medium",
    wikiPageLink: "/project-wiki",
    tags: ["sidebar", "keyboard", "accessibility"],
    milestone: "ph-1-2",
    details: "Validate keyboard navigation through sidebar destinations.",
  },
  {
    id: "task-13",
    isFinished: false,
    subject: "Task wiki autosave",
    status: "In Progress",
    dueDate: "2026-06-20",
    priority: "High",
    wikiPageLink: "/task-wiki",
    tags: ["wiki", "autosave", "editor"],
    milestone: "ph-1-3",
    details: "Persist task wiki edits automatically after short idle periods.",
  },
  {
    id: "task-14",
    isFinished: false,
    subject: "Project wiki table of contents",
    status: "Not Started",
    dueDate: "2026-06-22",
    priority: "Low",
    wikiPageLink: "/project-wiki",
    tags: ["wiki", "toc", "navigation"],
    milestone: "ph-1-3",
    details: "Generate a table of contents from project wiki headings.",
  },
  {
    id: "task-15",
    isFinished: false,
    subject: "Due date quick presets",
    status: "In Progress",
    dueDate: "2026-06-24",
    priority: "Medium",
    wikiPageLink: "/project-wiki",
    tags: ["due-date", "calendar", "presets"],
    milestone: "ph-1-3",
    details: "Add quick due date options such as today, tomorrow, and next week.",
  },
  {
    id: "task-16",
    isFinished: false,
    subject: "Priority color audit",
    status: "Review",
    dueDate: "2026-06-26",
    priority: "Low",
    wikiPageLink: "/project-wiki",
    tags: ["priority", "color", "accessibility"],
    milestone: "ph-1-3",
    details: "Check priority colors for contrast in light and dark themes.",
  },
  {
    id: "task-17",
    isFinished: false,
    subject: "Project export workflow",
    status: "Not Started",
    dueDate: "2026-06-28",
    priority: "High",
    wikiPageLink: "/project-wiki",
    tags: ["export", "project", "workflow"],
    milestone: "ph-1-4",
    details: "Define how project data can be exported for backup or sharing.",
  },
  {
    id: "task-18",
    isFinished: true,
    subject: "Empty state polish",
    status: "Review",
    dueDate: "2026-06-30",
    priority: "Medium",
    wikiPageLink: "/project-wiki",
    tags: ["empty-state", "ui", "polish"],
    milestone: "ph-1-4",
    details: "Improve empty states across project, tag, and search pages.",
  },
  {
    id: "task-19",
    isFinished: false,
    subject: "Notification preference panel",
    status: "In Progress",
    dueDate: "2026-07-02",
    priority: "Medium",
    wikiPageLink: "/project-wiki",
    tags: ["notifications", "settings", "preferences"],
    milestone: "ph-1-4",
    details: "Create notification preference controls in the settings page.",
  },
  {
    id: "task-20",
    isFinished: false,
    subject: "Tag color migration plan",
    status: "Not Started",
    dueDate: "2026-07-04",
    priority: "Low",
    wikiPageLink: "/project-wiki",
    tags: ["tag", "color", "migration"],
    milestone: "ph-1-4",
    details: "Plan how existing tag colors should migrate to the new palette.",
  },
  {
    id: "task-21",
    isFinished: false,
    subject: "Search ranking tuning",
    status: "In Progress",
    dueDate: "2026-07-06",
    priority: "High",
    wikiPageLink: "/project-wiki",
    tags: ["search", "ranking", "relevance"],
    milestone: "ph-1-5",
    details: "Tune search ranking so exact title matches appear first.",
  },
  {
    id: "task-22",
    isFinished: false,
    subject: "Task activity timeline",
    status: "Not Started",
    dueDate: "2026-07-08",
    priority: "Medium",
    wikiPageLink: "/task-wiki",
    tags: ["activity", "timeline", "task"],
    milestone: "ph-1-5",
    details: "Show task changes and comments in a chronological timeline.",
  },
  {
    id: "task-23",
    isFinished: true,
    subject: "Responsive grid check",
    status: "Review",
    dueDate: "2026-07-10",
    priority: "Medium",
    wikiPageLink: "/project-wiki",
    tags: ["responsive", "grid", "qa"],
    milestone: "ph-1-5",
    details: "Check the grid layout across desktop and narrow viewports.",
  },
  {
    id: "task-24",
    isFinished: false,
    subject: "Release checklist draft",
    status: "Not Started",
    dueDate: "2026-07-12",
    priority: "High",
    wikiPageLink: "/project-wiki",
    tags: ["release", "checklist", "planning"],
    milestone: "ph-1-5",
    details: "Draft the release checklist for the first ManageMe milestone.",
  },
];
